aaseat/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'aaseat'

urlpatterns = [
    url(r'^$', views.aaseat_dashboard, name='dashboard'),
    url(r'^addchar/$', views.aaseat_add_char, name='add_char'),
    url(r'^addcorp/$', views.aaseat_dashboard, name='add_corp')
]

aaseat/templates/aaseat/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{% trans "Dashboard" %}{% endblock %}
 {% block extra_css %}
 <style>
.flex-container {
    display: flex;
    flex-direction: row;
    height: 100%;
    align-items: center;
    justify-content: center;
}
.flex-wrap {
    display: -webkit-flex; /* Safari */
    -webkit-flex-wrap: wrap; /* Safari 6.1+ */
    display: flex;   
    flex-wrap: wrap;
}
.flex-item {

}
</style>
 {% endblock extra_css %}
{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "AA Seat" %}</h1>
        <div class="col-lg-10 col-lg-offset-1 container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <ul class="nav navbar-nav ">
                        <li><a href="{% url 'aaseat:add_char' %}">{% trans "Add New Character Token" %}</a></li>
                        <li><a href="{% url 'aaseat:add_corp' %}">{% trans "Add New Corporate Token" %}</a></li>
                    </ul>
                </div>
            </nav>
            {% block aaseat_block %}{% endblock %}
        </div>
    </div>
{% endblock %}

aaseat/templates/aaseat/dashboard.html
{% extends 'aaseat/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}

{% block aaseat_block %}
    {% if main_character %}
    <div class="container col-sm-12">
        <div class="row">
            <div class="col-sm-12 col-md-12 text-center">
            <h3>Main</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="col col-sm-4 col-md-4 text-center"><img class="ra-avatar img-circle" src="https://image.eveonline.com/Character/{{ main_character.character.character_id }}_128.jpg"><h4>{{ main_character.character.character_name }}</h4></div>
                <div class="col col-sm-4 col-md-4 text-center"><img class="ra-avatar img-circle" src="https://image.eveonline.com/Corporation/{{ main_character.character.corporation_id }}_128.png"><h4>{{ main_character.character.corporation_name }}</h4></div>
                <div class="text-center col col-sm-4 col-md-4">
                    <p>Skill Points <span class="badge badge-light">{{ main_character.total_sp|intcomma }}</span></p>
                    <p>Unalocated Skill Points <span class="badge badge-light">{{ main_character.unallocated_sp|intcomma }}</span></p>
                    <p>Total Isk <span class="badge badge-light">{{ main_character.wallet_balance|intcomma }}</span></p>
                    <p>Security Status <span class="badge badge-light">{{ main_character.sec_status|floatformat:2 }}</span></p>
                    <p>Last Known Location <span class="badge badge-light">{{ main_character.last_location|item }}</span></p>
                    <p>Last Known Ship <span class="badge badge-light">{{ main_character.last_ship_type|type_ }} ({{main_character.last_ship_name}})</span></p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12 text-center">
                <h3>Alts</h3>
            </div>
        </div>
        <div class="row">
            <div class="flex-container flex-wrap">
                {% if alts %}
                    {% for alt in alts%}
                        <div class=".flex-item text-center col-sm-4 col-md-3">
                            <img class="ra-avatar img-circle" src="https://image.eveonline.com/Character/{{ alt.character.character_id }}_128.jpg">
                            <h4>{{ alt.character.character_name }}</h4>
                            <div>
                                <p>Corp: <span class="badge badge-light">{{ alt.character.corporation_name }}</span></p>
                                {% if alt.total_sp  %}
                                    <p>Isk: <span class="badge badge-light">{{ alt.wallet_balance|intcomma }}</span></p>
                                    <p>Location: <span class="badge badge-light">{{ alt.last_location }}</span></p>
                                    <p>Ship: <span class="badge badge-light">{{ alt.last_ship_type }} ({{alt.last_ship_name}})</span></p>
                                {% else %}
                                    <div class="alert alert-warning text-center">{% trans "No Token Loaded" %}</div>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="alert alert-info text-center">{% trans "No Linked Alts." %}</div>
                {% endif %}
            </div>
        </div>
    </div>
    {% else %}
    <div class="alert alert-warning text-center">{% trans "No Tokens Loaded." %}</div>
    {% endif %}
    
{% endblock %}